// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Paranoid Zero.

//! Compact canonical runtime material for one frozen HistoryStep bank.
//!
//! The carrier retains only the four selected-Block outer slice tables and
//! the eight compiled transcript layouts. Every omitted schedule, purpose,
//! Merkle family and the parent Link VK itself is regenerated by checked
//! canonical constructors.

use noid_ivc_core::deep_chain::schedule::{DuplexLayout, DuplexSlot, LaneSource};
use noid_ivc_core::pcs::PcsParams;
use noid_ivc_core::public_io::WitnessSlice;

use super::{
    HistoryStepError, HistoryStepParentGeometry, HistoryStepParentTranscriptLayout,
    HistoryStepRuntimeParts,
};
use crate::acceptance::history_step_bank::{
    CanonicalHistoryStepClassId, HISTORY_STEP_TIER_SLOT_COUNT,
};
use crate::region_sidecar::{
    BlockRegionSidecarVk, SelectedZkBlockRegionVkSlices, DUPLEX_REGION_COMMITTED_COLUMNS,
    MERKLE_REGION_COMMITTED_COLUMNS, WALK_A_META_COMMITTED_COLUMNS,
    WALK_A_WALLET_COMMITTED_COLUMNS,
};

pub const HISTORY_STEP_RUNTIME_PARTS_COMPACT_VERSION: u8 = 1;
pub const HISTORY_STEP_RUNTIME_PARTS_COMPACT_MAX_BYTES: usize = 40 * 1024 * 1024;

const MAX_LAYOUT_SLOTS: usize = 1 << 17;
const MAX_LAYOUT_CHALLENGES: usize = 1 << 18;
const SLICE_BYTES: usize = 5;
const LAYOUT_HEADER_BYTES: usize = 12;
const LANE_BYTES: usize = 17;
const SLOT_BYTES: usize = 2 * LANE_BYTES;
const CHALLENGE_BYTES: usize = 5;
const BLOCK_SLICE_COUNT: usize = WALK_A_WALLET_COMMITTED_COLUMNS
    + WALK_A_META_COMMITTED_COLUMNS
    + 2 * MERKLE_REGION_COMMITTED_COLUMNS
    + 2 * DUPLEX_REGION_COMMITTED_COLUMNS;

fn encoding() -> HistoryStepError {
    HistoryStepError::WireEncoding
}

fn checked_add(left: usize, right: usize) -> Result<usize, HistoryStepError> {
    left.checked_add(right).ok_or_else(encoding)
}

fn checked_mul(left: usize, right: usize) -> Result<usize, HistoryStepError> {
    left.checked_mul(right).ok_or_else(encoding)
}

fn layout_len(layout: &DuplexLayout) -> Result<usize, HistoryStepError> {
    checked_add(
        checked_add(
            LAYOUT_HEADER_BYTES,
            checked_mul(layout.slots.len(), SLOT_BYTES)?,
        )?,
        checked_mul(layout.challenges.len(), CHALLENGE_BYTES)?,
    )
}

fn validate_layout(layout: &DuplexLayout) -> Result<(), HistoryStepError> {
    if layout.slots.is_empty()
        || layout.slots.len() > MAX_LAYOUT_SLOTS
        || layout.challenges.len() > MAX_LAYOUT_CHALLENGES
        || layout.n_data > layout.slots.len().saturating_mul(2)
    {
        return Err(encoding());
    }
    let mut next_data = 0usize;
    for slot in &layout.slots {
        for lane in slot.lanes {
            if let Some(LaneSource::Data(index)) = lane {
                if index != next_data {
                    return Err(encoding());
                }
                next_data = next_data.checked_add(1).ok_or_else(encoding)?;
            }
        }
    }
    if next_data != layout.n_data
        || layout
            .challenges
            .iter()
            .any(|(slot, lane)| *slot >= layout.slots.len() || *lane >= 2)
    {
        return Err(encoding());
    }
    Ok(())
}

fn put_u32(out: &mut Vec<u8>, value: usize) -> Result<(), HistoryStepError> {
    let value = u32::try_from(value).map_err(|_| encoding())?;
    out.extend_from_slice(&value.to_le_bytes());
    Ok(())
}

fn put_slice(out: &mut Vec<u8>, slice: WitnessSlice) -> Result<(), HistoryStepError> {
    out.push(u8::try_from(slice.log2_len).map_err(|_| encoding())?);
    put_u32(out, slice.index)
}

fn put_block_slices(
    out: &mut Vec<u8>,
    slices: SelectedZkBlockRegionVkSlices,
) -> Result<(), HistoryStepError> {
    for slice in slices
        .wallet_a
        .into_iter()
        .chain(slices.meta_a)
        .chain(slices.wallet_b)
        .chain(slices.meta_b)
        .chain(slices.owner_c)
        .chain(slices.main_c)
    {
        put_slice(out, slice)?;
    }
    Ok(())
}

fn put_layout(out: &mut Vec<u8>, layout: &DuplexLayout) -> Result<(), HistoryStepError> {
    validate_layout(layout)?;
    put_u32(out, layout.slots.len())?;
    put_u32(out, layout.challenges.len())?;
    put_u32(out, layout.n_data)?;
    for slot in &layout.slots {
        for lane in slot.lanes {
            match lane {
                None => {
                    out.push(0);
                    out.extend_from_slice(&0u128.to_le_bytes());
                }
                Some(LaneSource::Data(index)) => {
                    out.push(1);
                    out.extend_from_slice(&(index as u128).to_le_bytes());
                }
                Some(LaneSource::Const(value)) => {
                    out.push(2);
                    out.extend_from_slice(&value.to_le_bytes());
                }
            }
        }
    }
    for &(slot, lane) in &layout.challenges {
        put_u32(out, slot)?;
        out.push(u8::try_from(lane).map_err(|_| encoding())?);
    }
    Ok(())
}

#[derive(Clone, Copy)]
struct Reader<'a> {
    bytes: &'a [u8],
    position: usize,
}

impl<'a> Reader<'a> {
    fn new(bytes: &'a [u8]) -> Result<Self, HistoryStepError> {
        if bytes.is_empty() || bytes.len() > HISTORY_STEP_RUNTIME_PARTS_COMPACT_MAX_BYTES {
            return Err(encoding());
        }
        Ok(Self { bytes, position: 0 })
    }

    fn take(&mut self, count: usize) -> Result<&'a [u8], HistoryStepError> {
        let end = checked_add(self.position, count)?;
        let value = self.bytes.get(self.position..end).ok_or_else(encoding)?;
        self.position = end;
        Ok(value)
    }

    fn u8(&mut self) -> Result<u8, HistoryStepError> {
        Ok(self.take(1)?[0])
    }

    fn u32(&mut self) -> Result<usize, HistoryStepError> {
        Ok(u32::from_le_bytes(self.take(4)?.try_into().map_err(|_| encoding())?) as usize)
    }

    fn u128(&mut self) -> Result<u128, HistoryStepError> {
        Ok(u128::from_le_bytes(
            self.take(16)?.try_into().map_err(|_| encoding())?,
        ))
    }

    fn finish(self) -> Result<(), HistoryStepError> {
        if self.position == self.bytes.len() {
            Ok(())
        } else {
            Err(encoding())
        }
    }
}

fn preflight_layout(reader: &mut Reader<'_>) -> Result<(), HistoryStepError> {
    let slots = reader.u32()?;
    let challenges = reader.u32()?;
    let n_data = reader.u32()?;
    if slots == 0
        || slots > MAX_LAYOUT_SLOTS
        || challenges > MAX_LAYOUT_CHALLENGES
        || n_data > slots.saturating_mul(2)
    {
        return Err(encoding());
    }
    let mut next_data = 0usize;
    for _ in 0..slots * 2 {
        let tag = reader.u8()?;
        let value = reader.u128()?;
        match tag {
            0 if value == 0 => {}
            1 if value == next_data as u128 => {
                next_data = next_data.checked_add(1).ok_or_else(encoding)?;
            }
            2 => {}
            _ => return Err(encoding()),
        }
    }
    if next_data != n_data {
        return Err(encoding());
    }
    for _ in 0..challenges {
        if reader.u32()? >= slots || reader.u8()? >= 2 {
            return Err(encoding());
        }
    }
    Ok(())
}

fn preflight(encoded: &[u8]) -> Result<(), HistoryStepError> {
    let mut reader = Reader::new(encoded)?;
    if reader.u8()? != HISTORY_STEP_RUNTIME_PARTS_COMPACT_VERSION {
        return Err(HistoryStepError::WireVersion);
    }
    reader.take(
        HISTORY_STEP_TIER_SLOT_COUNT
            .checked_mul(BLOCK_SLICE_COUNT)
            .and_then(|count| count.checked_mul(SLICE_BYTES))
            .ok_or_else(encoding)?,
    )?;
    for _ in 0..HISTORY_STEP_TIER_SLOT_COUNT * 2 {
        preflight_layout(&mut reader)?;
    }
    reader.finish()
}

fn read_slice(reader: &mut Reader<'_>) -> Result<WitnessSlice, HistoryStepError> {
    Ok(WitnessSlice {
        log2_len: reader.u8()? as usize,
        index: reader.u32()?,
    })
}

fn read_array<const N: usize>(
    reader: &mut Reader<'_>,
) -> Result<[WitnessSlice; N], HistoryStepError> {
    let mut slices = Vec::with_capacity(N);
    for _ in 0..N {
        slices.push(read_slice(reader)?);
    }
    slices.try_into().map_err(|_| encoding())
}

fn read_block_slices(
    reader: &mut Reader<'_>,
) -> Result<SelectedZkBlockRegionVkSlices, HistoryStepError> {
    Ok(SelectedZkBlockRegionVkSlices {
        wallet_a: read_array(reader)?,
        meta_a: read_array(reader)?,
        wallet_b: read_array(reader)?,
        meta_b: read_array(reader)?,
        owner_c: read_array(reader)?,
        main_c: read_array(reader)?,
    })
}

fn read_layout(reader: &mut Reader<'_>) -> Result<DuplexLayout, HistoryStepError> {
    let slots_len = reader.u32()?;
    let challenges_len = reader.u32()?;
    let n_data = reader.u32()?;
    let mut slots = Vec::with_capacity(slots_len);
    for _ in 0..slots_len {
        let mut lanes = [None, None];
        for lane in &mut lanes {
            let tag = reader.u8()?;
            let value = reader.u128()?;
            *lane = match tag {
                0 if value == 0 => None,
                1 => Some(LaneSource::Data(
                    usize::try_from(value).map_err(|_| encoding())?,
                )),
                2 => Some(LaneSource::Const(value)),
                _ => return Err(encoding()),
            };
        }
        slots.push(DuplexSlot { lanes });
    }
    let mut challenges = Vec::with_capacity(challenges_len);
    for _ in 0..challenges_len {
        challenges.push((reader.u32()?, reader.u8()? as usize));
    }
    let layout = DuplexLayout {
        slots,
        challenges,
        n_data,
    };
    validate_layout(&layout)?;
    Ok(layout)
}

impl HistoryStepRuntimeParts {
    pub fn compact_encoded_len(&self) -> Result<usize, HistoryStepError> {
        let mut len = checked_add(
            1,
            checked_mul(
                HISTORY_STEP_TIER_SLOT_COUNT * BLOCK_SLICE_COUNT,
                SLICE_BYTES,
            )?,
        )?;
        for transcript in self.parent_transcripts() {
            len = checked_add(len, layout_len(transcript.child())?)?;
            len = checked_add(len, layout_len(transcript.r_prev())?)?;
        }
        if len > HISTORY_STEP_RUNTIME_PARTS_COMPACT_MAX_BYTES {
            return Err(encoding());
        }
        Ok(len)
    }

    pub fn encode_compact(&self) -> Result<Vec<u8>, HistoryStepError> {
        let mut encoded = Vec::with_capacity(self.compact_encoded_len()?);
        encoded.push(HISTORY_STEP_RUNTIME_PARTS_COMPACT_VERSION);
        for vk in self.direct_block_vks() {
            put_block_slices(&mut encoded, vk.selected_registry_slices()?)?;
        }
        for transcript in self.parent_transcripts() {
            put_layout(&mut encoded, transcript.child())?;
            put_layout(&mut encoded, transcript.r_prev())?;
        }
        if encoded.len() != self.compact_encoded_len()? {
            return Err(encoding());
        }
        Ok(encoded)
    }

    pub fn decode_compact(encoded: &[u8]) -> Result<Self, HistoryStepError> {
        // The first pass proves the complete byte extent and every allocation
        // bound before the second pass reserves a vector.
        preflight(encoded)?;
        let mut reader = Reader::new(encoded)?;
        if reader.u8()? != HISTORY_STEP_RUNTIME_PARTS_COMPACT_VERSION {
            return Err(HistoryStepError::WireVersion);
        }
        let mut direct_block_vks = Vec::with_capacity(HISTORY_STEP_TIER_SLOT_COUNT);
        for slot in 0..HISTORY_STEP_TIER_SLOT_COUNT {
            let tier = noid_chain::consensus::params::BLOCK_PAGE_CLASS_TIERS[slot];
            direct_block_vks.push(BlockRegionSidecarVk::from_selected_registry_slices(
                tier,
                read_block_slices(&mut reader)?,
            )?);
        }
        let direct_block_vks: [BlockRegionSidecarVk; HISTORY_STEP_TIER_SLOT_COUNT] =
            direct_block_vks.try_into().map_err(|_| encoding())?;
        let mut parent_transcripts = Vec::with_capacity(HISTORY_STEP_TIER_SLOT_COUNT);
        for _ in 0..HISTORY_STEP_TIER_SLOT_COUNT {
            parent_transcripts.push(HistoryStepParentTranscriptLayout::new(
                read_layout(&mut reader)?,
                read_layout(&mut reader)?,
            ));
        }
        reader.finish()?;
        let parent_transcripts: [HistoryStepParentTranscriptLayout; HISTORY_STEP_TIER_SLOT_COUNT] =
            parent_transcripts.try_into().map_err(|_| encoding())?;
        let parent_params: [PcsParams; HISTORY_STEP_TIER_SLOT_COUNT] =
            std::array::from_fn(|slot| {
                crate::acceptance::history_step_bank::canonical_history_step_pcs_params(
                    CanonicalHistoryStepClassId::new(slot)
                        .expect("canonical HistoryStep tier slot"),
                )
            });
        let geometry = HistoryStepParentGeometry::new(
            &parent_params,
            parent_transcripts
                .iter()
                .map(|transcript| transcript.child().clone())
                .collect(),
            parent_transcripts
                .iter()
                .map(|transcript| transcript.r_prev().clone())
                .collect(),
        )?;
        let parent_recursion_vk = geometry
            .canonical_vk(&crate::acceptance::history_step_bank::history_step_bank_io_spec())?;
        Ok(HistoryStepRuntimeParts::from_canonical_geometry(
            parent_recursion_vk,
            direct_block_vks,
            parent_transcripts,
            geometry,
        ))
    }
}

impl super::v2::V2RuntimeParts {
    pub fn encode_compact(&self) -> Result<Vec<u8>, super::v2::V2Error> {
        let expected = 8
            + 40
            + BLOCK_SLICE_COUNT * SLICE_BYTES
            + layout_len(self.child_layout())?
            + layout_len(self.parent_layout())?;
        if expected > HISTORY_STEP_RUNTIME_PARTS_COMPACT_MAX_BYTES {
            return Err(encoding().into());
        }
        let mut out = Vec::with_capacity(expected);
        out.extend_from_slice(b"O1V2PT02");
        let config = self.config();
        for value in [
            config.outer_m() as u64,
            config.pages() as u64,
            config.schedule().v1_1_height().unwrap(),
            config.activation_height(),
            config.block_time(),
        ] {
            out.extend_from_slice(&value.to_le_bytes());
        }
        put_block_slices(&mut out, self.block_vk().selected_registry_slices()?)?;
        put_layout(&mut out, self.child_layout())?;
        put_layout(&mut out, self.parent_layout())?;
        if out.len() != expected {
            return Err(encoding().into());
        }
        Ok(out)
    }

    /// Decode an externally pinned one-class recipe. This cannot reinterpret
    /// old Meta tables as object tables or old two-arm transcripts as v2.
    pub fn decode_compact(encoded: &[u8]) -> Result<Self, super::v2::V2Error> {
        let mut preflight = Reader::new(encoded)?;
        if preflight.take(8)? != b"O1V2PT02" {
            return Err(encoding().into());
        }
        preflight.take(40)?;
        preflight.take(BLOCK_SLICE_COUNT * SLICE_BYTES)?;
        preflight_layout(&mut preflight)?;
        preflight_layout(&mut preflight)?;
        preflight.finish()?;
        let mut reader = Reader::new(encoded)?;
        reader.take(8)?;
        let mut values = [0u64; 5];
        for value in &mut values {
            *value = u64::from_le_bytes(reader.take(8)?.try_into().map_err(|_| encoding())?);
        }
        let activation = noid_chain::consensus::forks::V2Activation::new(values[3], values[4])
            .ok_or_else(encoding)?;
        let schedule =
            noid_chain::consensus::forks::ForkSchedule::new(Some(values[2]), Some(activation))
                .ok_or_else(encoding)?;
        let config = super::v2::V2Config::new(
            usize::try_from(values[0]).map_err(|_| encoding())?,
            usize::try_from(values[1]).map_err(|_| encoding())?,
            schedule,
        )?;
        let block = BlockRegionSidecarVk::from_object_registry_slices(
            config.pages(),
            read_block_slices(&mut reader)?,
        )?;
        let child = read_layout(&mut reader)?;
        let parent = read_layout(&mut reader)?;
        reader.finish()?;
        Self::new(config, block, child, parent)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use noid_ivc_core::deep_chain::schedule::{compile_duplex, TranscriptOp};

    #[test]
    fn layout_codec_roundtrip_is_canonical() {
        let layout = compile_duplex(&[
            TranscriptOp::Absorb(vec![None, Some(7), None]),
            TranscriptOp::Squeeze(3),
            TranscriptOp::Absorb(vec![None]),
            TranscriptOp::Squeeze(1),
        ]);
        let mut bytes = Vec::new();
        put_layout(&mut bytes, &layout).unwrap();
        let mut reader = Reader::new(&bytes).unwrap();
        preflight_layout(&mut reader).unwrap();
        reader.finish().unwrap();
        let mut reader = Reader::new(&bytes).unwrap();
        assert_eq!(read_layout(&mut reader).unwrap(), layout);
        reader.finish().unwrap();
    }

    #[test]
    fn layout_preflight_rejects_oversize_before_allocation() {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&u32::try_from(MAX_LAYOUT_SLOTS + 1).unwrap().to_le_bytes());
        bytes.extend_from_slice(&0u32.to_le_bytes());
        bytes.extend_from_slice(&0u32.to_le_bytes());
        let mut reader = Reader::new(&bytes).unwrap();
        assert!(preflight_layout(&mut reader).is_err());
    }
}
